SUPABASE_URL="https://lwkrsniacyddadioibny.supabase.co"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3a3JzbmlhY3lkZGFkaW9pYm55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNzU5NzEsImV4cCI6MjA3Mzg1MTk3MX0.4SmzzdrloSZQQfKAmXfgfJcbOEwaxHH6cLeQ3A0q9aM"

Admin="admin123"
